#!/usr/bin/env bash
# main-model.sh — ONE global toggle for the whole fleet.
# Points every consumer/agent alias (main, orchestrator, qwen-routing, generalist, coder,
# smart, ...) at a single chosen big model, so ALL Hermes agents + OpenCode/Cline switch
# together. No smart/embedding routing.
#
#   ./main-model.sh              fzf MENU of models -> pick -> switch the whole fleet
#   ./main-model.sh <name>       direct switch (minimax|mistral|qwen3.6|gemma4)
#   ./main-model.sh show         current active model + what's loaded
#
# Regenerates llama-cpp/config.yaml (deterministic) and llama-swap hot-reloads (-watch-config).
# qwen3-vl stays available as the explicit `visual` model. To add a model: one line in MODELS + ORDER.
set -euo pipefail

DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"   # resolve symlink so `main-model` in PATH works
CONFIG="$DIR/llama-cpp/config.yaml"
STATE="$DIR/.main-model"
SWAP="http://127.0.0.1:11434"
CTX=65536   # every menu model serves this; agents set context_length: 65536 to match

# --- model registry: name -> the "-m/-hf ... + sampling" flags (after the common prefix) ---
declare -A MODELS=(
  [minimax]="-m /mnt/AI_Models/gguf/minimax/UD-Q3_K_S/MiniMax-M2.7-UD-Q3_K_S-00001-of-00003.gguf -ngl 999 -c $CTX -b 256 --cache-type-k q8_0 --cache-type-v q8_0 --temp 1.0 --top-p 0.95 --min-p 0.01 --top-k 40"
  [mistral]="-m /mnt/AI_Models/gguf/mistral3/Q4_K_M/Mistral-Medium-3.5-128B-Q4_K_M-00001-of-00003.gguf -ngl 999 -c $CTX --temp 0.7 --top-p 0.8"
  [qwen3.6]="-hf unsloth/Qwen3.6-27B-GGUF:UD-Q4_K_XL -ngl 999 -c $CTX --temp 0.7 --top-p 0.8 --top-k 20"
  [gemma4]="-hf unsloth/gemma-4-31B-it-GGUF:Q4_K_M -ngl 999 -c $CTX --temp 1.0 --top-p 0.95 --top-k 64"
)
ORDER=(minimax mistral qwen3.6 gemma4)

# explicit per-model aliases (always on that model, regardless of the toggle)
declare -A BASE_ALIASES=(
  [minimax]='"minimax-m2.7", "ollama/minimax"'
  [mistral]='"mistral-medium-3.5", "ollama/mistral"'
  [qwen3.6]='"qwen-3.6", "ollama/qwen3.6"'
  [gemma4]='"gemma-4", "ollama/gemma4"'
)
# consumer/agent aliases that FOLLOW the toggle (land on the active model)
CONSUMER='"main", "orchestrator", "qwen-routing", "custom/ollama/orchestrator", "ollama/orchestrator", "generalist", "coder", "agent", "hermes", "smart", "ollama/smart", "ollama/generalist"'

emit_model() { # $1=name $2=", extra aliases" or ""
  cat <<EOF
  "$1":
    aliases: [${BASE_ALIASES[$1]}$2]
    cmd: |
      llama-server --host :: --port \${PORT} -fa on --jinja --no-mmap ${MODELS[$1]}
    ttl: 0
EOF
}

write_config() { # $1=active model
  local active="$1" m
  {
    echo "# GENERATED by main-model.sh — active main model: $active  (edit MODELS/ORDER in the script)"
    echo "healthCheckTimeout: 1200"
    echo "logLevel: info"
    echo "models:"
    for m in "${ORDER[@]}"; do
      [ "$m" = "$active" ] && emit_model "$m" ", $CONSUMER" || emit_model "$m" ""
    done
    cat <<EOF
  "qwen3-vl":
    aliases: ["visual", "vision", "image", "ollama/visual", "ollama/vision"]
    cmd: |
      llama-server --host :: --port \${PORT} -fa on --jinja --no-mmap -hf unsloth/Qwen3-VL-8B-Instruct-GGUF:Q4_K_M -ngl 999 -c 16384
    ttl: 900
groups:
  # ONE big "main" model resident at a time.
  "big":
    swap: true
    exclusive: false
    members: [$(printf '"%s", ' "${ORDER[@]}" | sed 's/, $//')]
  # Vision: Qwen3-VL loads ON DEMAND when an image is sent to visual/vision/image, then
  # unloads after 15min idle (ttl:900). NOT permanently resident — frees RAM when unused.
  # (Mistral's own mmproj vision was tried and doesn't work reliably in this build + OOM-heavy.)
  "vision":
    swap: false
    exclusive: false
    persistent: false
    members: ["qwen3-vl"]
EOF
  } > "$CONFIG"
}

switch() { # $1=target — clean swap: free the old model, rewrite config, restart, wait for ready
  printf '%s\n' "${ORDER[@]}" | grep -qx "$1" || { echo "unknown model: $1 (have: ${ORDER[*]})"; exit 1; }
  echo "main -> $1"
  # 1) rewrite config so the new model is the active `main`
  write_config "$1"; echo "$1" > "$STATE"
  # 2) restart llama-swap: this FULLY frees the currently-loaded model before the new one loads,
  #    which avoids the transient OOM when swapping between two big models (both briefly resident).
  echo "  restarting llama-swap (frees the old model first — no OOM overlap)..."
  systemctl --user restart llama-swap.service 2>/dev/null \
    || { echo "  ! could not restart llama-swap (user service). Config is set; it will apply on next start."; return 1; }
  # 3) the unit's ExecStartPost warms `main` (=$1); wait for it to become ready
  printf "  loading %s " "$1"
  local i
  for i in $(seq 1 300); do
    if curl -s -m3 "$SWAP/running" 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); sys.exit(0 if any(m.get('model')=='$1' and m.get('state')=='ready' for m in d.get('running',[])) else 1)" 2>/dev/null; then
      echo " ready."; return 0
    fi
    printf '.'; sleep 2
  done
  echo " (still loading — watch: journalctl --user -u llama-swap -f)"
}

show() {
  echo "active main model: $(cat "$STATE" 2>/dev/null || echo '(unset)')"
  echo "loaded: $(curl -s -m5 "$SWAP/running" 2>/dev/null | python3 -c 'import json,sys;print([m["model"] for m in json.load(sys.stdin).get("running",[])])' 2>/dev/null || echo '(llama-swap unreachable)')"
}

menu() {
  command -v fzf >/dev/null || { echo "fzf not found; use: $0 <${ORDER[*]}>"; exit 1; }
  local cur pick; cur=$(cat "$STATE" 2>/dev/null || echo '')
  pick=$(for m in "${ORDER[@]}"; do [ "$m" = "$cur" ] && echo "$m  (current)" || echo "$m"; done \
         | fzf --prompt='global main model > ' --height=45% --reverse --header='Switch the whole Hermes fleet + local tools to:') || exit 0
  pick=${pick%%  (current)}; pick=$(echo "$pick" | awk '{print $1}')
  [ -n "$pick" ] && { switch "$pick"; echo; read -rp "Press Enter to close..." _; }
}

case "${1:-menu}" in
  menu|"") menu ;;
  show)    show ;;
  *)       switch "$1" ;;
esac
