#!/usr/bin/env bash
# main-model.sh — ONE global toggle for the whole fleet.
# Points every consumer/agent alias (main, orchestrator, qwen-routing, generalist, coder,
# smart, ...) at a single chosen big model, so ALL Hermes agents + OpenCode/Cline switch
# together. No smart/embedding routing.
#
#   ./main-model.sh              fzf MENU of models -> pick -> switch the whole fleet
#   ./main-model.sh <name>       direct switch (minimax|mistral|qwen3.6|gemma4)
#   ./main-model.sh show         current active model + what's loaded
#
# Regenerates llama-cpp/config.yaml (deterministic) and llama-swap hot-reloads (-watch-config).
# qwen3-vl stays available as the explicit `visual` model. To add a model: one line in MODELS + ORDER.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$DIR/llama-cpp/config.yaml"
STATE="$DIR/.main-model"
SWAP="http://127.0.0.1:11434"
CTX=65536   # every menu model serves this; agents set context_length: 65536 to match

# --- model registry: name -> the "-m/-hf ... + sampling" flags (after the common prefix) ---
declare -A MODELS=(
  [minimax]="-m /mnt/AI_Models/gguf/minimax/UD-Q3_K_S/MiniMax-M2.7-UD-Q3_K_S-00001-of-00003.gguf -ngl 999 -c $CTX -b 256 --cache-type-k q8_0 --cache-type-v q8_0 --temp 1.0 --top-p 0.95 --min-p 0.01 --top-k 40"
  [mistral]="-m /mnt/AI_Models/gguf/mistral3/Q4_K_M/Mistral-Medium-3.5-128B-Q4_K_M-00001-of-00003.gguf -ngl 999 -c $CTX --temp 0.7 --top-p 0.8"
  [qwen3.6]="-hf unsloth/Qwen3.6-27B-GGUF:UD-Q4_K_XL -ngl 999 -c $CTX --temp 0.7 --top-p 0.8 --top-k 20"
  [gemma4]="-hf unsloth/gemma-4-31B-it-GGUF:Q4_K_M -ngl 999 -c $CTX --temp 1.0 --top-p 0.95 --top-k 64"
)
ORDER=(minimax mistral qwen3.6 gemma4)

# explicit per-model aliases (always on that model, regardless of the toggle)
declare -A BASE_ALIASES=(
  [minimax]='"minimax-m2.7", "ollama/minimax"'
  [mistral]='"mistral-medium-3.5", "ollama/mistral"'
  [qwen3.6]='"qwen-3.6", "ollama/qwen3.6"'
  [gemma4]='"gemma-4", "ollama/gemma4"'
)
# consumer/agent aliases that FOLLOW the toggle (land on the active model)
CONSUMER='"main", "orchestrator", "qwen-routing", "custom/ollama/orchestrator", "ollama/orchestrator", "generalist", "coder", "agent", "hermes", "smart", "ollama/smart", "ollama/generalist"'

emit_model() { # $1=name $2=", extra aliases" or ""
  cat <<EOF
  "$1":
    aliases: [${BASE_ALIASES[$1]}$2]
    cmd: |
      llama-server --host :: --port \${PORT} -fa on --jinja --no-mmap ${MODELS[$1]}
    ttl: 0
EOF
}

write_config() { # $1=active model
  local active="$1" m
  {
    echo "# GENERATED by main-model.sh — active main model: $active  (edit MODELS/ORDER in the script)"
    echo "healthCheckTimeout: 1200"
    echo "logLevel: info"
    echo "models:"
    for m in "${ORDER[@]}"; do
      [ "$m" = "$active" ] && emit_model "$m" ", $CONSUMER" || emit_model "$m" ""
    done
    cat <<EOF
  "qwen3-vl":
    aliases: ["visual", "vision", "image", "ollama/visual", "ollama/vision"]
    cmd: |
      llama-server --host :: --port \${PORT} -fa on --jinja --no-mmap -hf unsloth/Qwen3-VL-8B-Instruct-GGUF:Q4_K_M -ngl 999 -c 16384
    ttl: 0
groups:
  "big":
    swap: true
    exclusive: false
    members: [$(printf '"%s", ' "${ORDER[@]}" | sed 's/, $//')]
  "always":
    swap: false
    exclusive: false
    persistent: true
    members: ["qwen3-vl"]
EOF
  } > "$CONFIG"
}

warm() { # $1=model — switch + warm immediately, showing progress
  echo "main -> $1  (config regenerated; llama-swap hot-reloads in ~2s)"
  echo "warming $1 (loading into GPU — big models take a few minutes)..."
  ( curl -s -m 1800 "$SWAP/v1/chat/completions" -H 'Content-Type: application/json' \
      -d "{\"model\":\"main\",\"messages\":[{\"role\":\"user\",\"content\":\"hi\"}],\"max_tokens\":1}" >/dev/null 2>&1 ) &
  local pid=$! i=0
  while kill -0 "$pid" 2>/dev/null; do
    printf '\r  loading %s %s' "$1" "$(printf '%.*s' $((i%4)) '....')   "; i=$((i+1)); sleep 1
  done
  if curl -s -m5 "$SWAP/running" 2>/dev/null | grep -q "\"$1\""; then echo -e "\r  $1 is loaded and ready.        "; else echo -e "\r  warm finished (check: journalctl --user -u llama-swap -f)"; fi
}

switch() {
  printf '%s\n' "${ORDER[@]}" | grep -qx "$1" || { echo "unknown model: $1 (have: ${ORDER[*]})"; exit 1; }
  write_config "$1"; echo "$1" > "$STATE"; sleep 2; warm "$1"
}

show() {
  echo "active main model: $(cat "$STATE" 2>/dev/null || echo '(unset)')"
  echo "loaded: $(curl -s -m5 "$SWAP/running" 2>/dev/null | python3 -c 'import json,sys;print([m["model"] for m in json.load(sys.stdin).get("running",[])])' 2>/dev/null || echo '(llama-swap unreachable)')"
}

menu() {
  command -v fzf >/dev/null || { echo "fzf not found; use: $0 <${ORDER[*]}>"; exit 1; }
  local cur pick; cur=$(cat "$STATE" 2>/dev/null || echo '')
  pick=$(for m in "${ORDER[@]}"; do [ "$m" = "$cur" ] && echo "$m  (current)" || echo "$m"; done \
         | fzf --prompt='global main model > ' --height=45% --reverse --header='Switch the whole Hermes fleet + local tools to:') || exit 0
  pick=${pick%%  (current)}; pick=$(echo "$pick" | awk '{print $1}')
  [ -n "$pick" ] && { switch "$pick"; echo; read -rp "Press Enter to close..." _; }
}

case "${1:-menu}" in
  menu|"") menu ;;
  show)    show ;;
  *)       switch "$1" ;;
esac
