#!/usr/bin/env python3
"""Hardware-owned llama-swap registries, selection, and live fleet budgets."""
import argparse
import fcntl
import json
import os
from pathlib import Path
import shlex
import socket
import subprocess
import sys
import tempfile
import time
import urllib.request

ROOT = Path(__file__).resolve().parents[1]


def atomic(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=path.name + ".")
    try:
        with os.fdopen(fd, "w") as out:
            out.write(text)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def render(registry, active):
    models = registry["models"]
    if active not in models:
        raise ValueError(f"unknown model: {active}")
    lines = ["# GENERATED by shared/modelctl.py; edit the hardware models.json",
             "healthCheckTimeout: 1800", "logLevel: info", "models:"]
    for key, model in models.items():
        aliases = model.get("aliases", []) + (registry["aliases"] if key == active else [])
        args = [registry["binary"], "--host", "::", "--port", "${PORT}",
                "-fa", "on", "--jinja", *registry.get("extra_args", []),
                *model["args"], "-c", str(model["context"] * model["slots"]),
                "--parallel", str(model["slots"])]
        # llama-swap replaces ${PORT} before executing the command.
        lines += [f"  {json.dumps(key)}:", f"    aliases: {json.dumps(aliases)}",
                  "    cmd: |", "      " + shlex.join(args), "    ttl: 0",
                  f"    concurrencyLimit: {model['slots']}"]
    lines += ["groups:", "  hardware:", "    swap: true", "    exclusive: true",
              f"    members: {json.dumps(list(models))}"]
    return "\n".join(lines) + "\n"


def api(reg, path, body=None, timeout=5):
    data = None if body is None else json.dumps(body).encode()
    req = urllib.request.Request(f"http://127.0.0.1:{reg['port']}{path}", data=data,
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as res:
        # llama-swap's health endpoint is plain text, unlike its model APIs.
        if path == "/health":
            return res.read().decode().strip()
        return json.load(res)


def current(reg):
    # /running is authoritative: a client can request a concrete model directly.
    running = api(reg, "/running").get("running", [])
    ready = [m["model"] for m in running if m.get("state") == "ready"]
    if len(ready) != 1 or ready[0] not in reg["models"]:
        raise RuntimeError("no single registered model is ready; fleet budget unavailable")
    return ready[0]


def restart(reg):
    if "container" in reg:
        subprocess.run(["docker", "restart", reg["container"]], check=True,
                       stdout=subprocess.DEVNULL)
    else:
        subprocess.run(["systemctl", "--user", "restart", reg["service"]], check=True)


def warm(reg, key):
    if key not in reg["models"] and key not in reg["aliases"]:
        raise ValueError(f"unknown warmup model: {key}")
    for _ in range(30):
        try:
            api(reg, "/health")
            break
        except Exception:
            time.sleep(1)
    else:
        raise RuntimeError("model proxy did not become healthy for warmup")
    response = api(reg, "/v1/chat/completions", {
        "model": key, "messages": [{"role": "user", "content": "Reply OK."}],
        "max_tokens": 32, "chat_template_kwargs": {"enable_thinking": False}}, timeout=1800)
    if not response.get("choices"):
        raise RuntimeError(f"warmup did not return a completion: {response}")
    ready = current(reg)
    if key in reg["models"] and ready != key:
        raise RuntimeError("warmup finished without the selected model ready")


def switch(reg, key):
    config = ROOT / reg["config"]
    state = ROOT / reg["state"]
    previous = config.read_text() if config.exists() else None
    previous_key = state.read_text().strip() if state.exists() else None
    # Validate the complete replacement before disturbing the running model.
    text = render(reg, key)
    try:
        # Stop first: watch-config must not race a rewrite and leave old weights resident.
        if "container" in reg:
            subprocess.run(["docker", "stop", reg["container"]], check=True,
                           stdout=subprocess.DEVNULL)
        else:
            subprocess.run(["systemctl", "--user", "stop", reg["service"]], check=True)
        atomic(config, text)
        restart(reg)
        warm(reg, key)
        atomic(state, key + "\n")
        print(f"{reg['aliases'][0]} -> {key}: ready", flush=True)
    except Exception:
        if previous is not None:
            print("Switch failed; restoring previous configuration.", file=sys.stderr, flush=True)
            atomic(config, previous)
            restart(reg)
            if previous_key:
                warm(reg, previous_key)
        raise


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("hardware", choices=["geekom", "7900xt", "rtx5080"])
    parser.add_argument("command", nargs="?", default="menu")
    parser.add_argument("model", nargs="?")
    a = parser.parse_args()
    reg = json.loads((ROOT / a.hardware / "models.json").read_text())
    state = ROOT / reg["state"]
    selected = state.read_text().strip() if state.exists() else "(unset)"
    command = a.command
    if command == "list":
        for name, model in reg["models"].items():
            print(f"{'*' if name == selected else ' '} {name:24} {model['slots']} x "
                  f"{model['context']} tokens; {model['reserved']} reserved")
        return
    if command == "render":
        print(render(reg, a.model or selected), end="")
        return
    if command in ("slots", "reserved", "context", "budget"):
        key = current(reg)
        model = reg["models"][key]
        if command == "budget":
            print(json.dumps({"model": key, **{k: model[k] for k in ("slots", "reserved", "context")},
                              "agents": max(0, model["slots"] - model["reserved"])}))
        else:
            print(model[command])
        return
    if command in ("show", "status"):
        print(f"selected {a.hardware}: {selected}")
        print(json.dumps(api(reg, "/running"), indent=2))
        return
    if socket.gethostname().split(".")[0] != reg["host"]:
        raise RuntimeError(f"run {a.hardware} on {reg['host']}")
    if command == "warm":
        # During a switch, state still records the last successful selection.
        # The hardware alias follows the new proxy config, so startup warmup
        # must use that alias rather than loading the previous model again.
        warm(reg, a.model or reg["aliases"][0])
        return
    if command == "menu":
        names = list(reg["models"])
        if sys.stdin.isatty():
            for i, name in enumerate(names, 1):
                print(f"{i}. {name}{' (selected)' if name == selected else ''}")
            choice = input("Select model number or name (blank cancels): ").strip()
            if not choice:
                return
            command = names[int(choice)-1] if choice.isdigit() and 0 < int(choice) <= len(names) else choice
        else:
            raise RuntimeError("interactive menu needs a terminal; use list or a model name")
    key = (a.model or selected) if command in ("config", "switch") else command
    # Retain old selection spellings while advertising only the rationalised registry.
    key = {"qwen3.8-fast": "qwen3.8-medium", "qwen3.8-fast-128k": "qwen3.8-medium-128k",
           "qwen38": "qwen3.8", "vision": "ocr"}.get(key, key)
    if a.hardware == "geekom" and key == "qwen3.8":
        key = "qwen3.8-medium"
    if key not in reg["models"]:
        raise ValueError(f"unknown model {key}; use list")
    with (ROOT / ("." + a.hardware + ".lock")).open("w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        if command == "config":
            # Provisioning only. Never trigger watch-config against a resident model.
            try:
                running = api(reg, "/running").get("running", [])
            except OSError:
                running = []
            if running:
                raise RuntimeError("models are resident; use switch instead of config")
            atomic(ROOT / reg["config"], render(reg, key))
            atomic(state, key + "\n")
        else:
            switch(reg, key)


if __name__ == "__main__":
    try:
        main()
    except (Exception, KeyboardInterrupt) as exc:
        print(f"modelctl: {exc}", file=sys.stderr)
        sys.exit(1)
