#!/usr/bin/env python3
"""Hardware-owned llama-swap registries, selection, and live fleet budgets."""
import argparse
import copy
import fcntl
import json
import os
from pathlib import Path
import shlex
import socket
import subprocess
import sys
import tempfile
import time
import urllib.request
import urllib.error
from urllib.parse import quote, urlparse

ROOT = Path(__file__).resolve().parents[1]


def atomic(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=path.name + ".")
    try:
        with os.fdopen(fd, "w") as out:
            out.write(text)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def effective_models(registry, preset="capacity"):
    presets = registry.get("presets", {"capacity": {}})
    if preset not in presets:
        raise ValueError(f"unknown preset {preset}; use presets")
    if presets[preset].get("disabled_reason"):
        raise ValueError("preset unavailable: " + presets[preset]["disabled_reason"])
    models = copy.deepcopy(registry["models"])
    for key, override in presets[preset].get("models", {}).items():
        if key not in models:
            raise ValueError(f"preset references unknown model {key}")
        model = models[key]
        args = model["args"]
        for flag in override.get("remove_flags", []):
            while flag in args:
                args.remove(flag)
        args.extend(override.get("append_args", []))
        for field in ("context", "slots", "reserved"):
            if field in override:
                model[field] = override[field]
    for model in models.values():
        if (type(model["slots"]) is not int or model["slots"] < 1 or
                type(model["context"]) is not int or model["context"] < 4096 or
                type(model["reserved"]) is not int or not 0 <= model["reserved"] <= model["slots"]):
            raise ValueError("invalid context/slot/reservation geometry")
    return models


def selection_options(registry):
    """Selectable model/resource pairs, omitting disabled and comparison-only presets."""
    result = []
    for model in registry["models"]:
        for name, preset in registry.get("presets", {"capacity": {}}).items():
            if preset.get("disabled_reason") or preset.get("comparison_only"):
                continue
            if name == "capacity" or model in preset.get("models", {}):
                result.append((model, name))
    return result


def print_options(registry, selected, saved_preset):
    for number, (key, preset) in enumerate(selection_options(registry), 1):
        model = effective_models(registry, preset)[key]
        marker = " *" if (key, preset) == (selected, saved_preset) else ""
        experimental = " [experimental]" if registry.get("presets", {}).get(preset, {}).get("experimental") else ""
        kv = "CPU KV" if "--no-kv-offload" in model["args"] else "GPU KV"
        print(f"{number}. {key}@{preset}: {model['slots']} x {model['context']} tokens; "
              f"{model['reserved']} reserved; {kv}{experimental}{marker}")


def resolve_option(registry, value):
    if value.isdigit():
        options = selection_options(registry)
        number = int(value)
        if not 1 <= number <= len(options):
            raise ValueError("model option number is out of range; use options")
        return options[number - 1]
    if "@" in value:
        key, preset = value.split("@", 1)
        if (key, preset) not in selection_options(registry):
            raise ValueError("unknown model/resource option; use options")
        return key, preset
    return value, None


def selection(reg):
    state = ROOT / reg["state"]
    model = state.read_text().strip() if state.exists() else "(unset)"
    saved = ROOT / ("." + reg["aliases"][0] + "-selection.json")
    if saved.exists():
        choice = json.loads(saved.read_text())
        if choice["model"] == model:
            return model, choice["preset"]
        raise RuntimeError("selection state disagrees; restore through the controller")
    return model, "capacity"


def save_selection(reg, key, preset):
    # The JSON record is authoritative only when the compatibility model agrees.
    atomic(ROOT / reg["state"], key + "\n")
    atomic(ROOT / ("." + reg["aliases"][0] + "-selection.json"),
           json.dumps({"model": key, "preset": preset}) + "\n")


def render(registry, active, preset="capacity", admission=False):
    models = effective_models(registry, preset)
    if active not in models:
        raise ValueError(f"unknown model: {active}")
    lines = ["# GENERATED by shared/modelctl.py; edit the hardware models.json",
             "healthCheckTimeout: 1800", "logLevel: info", "models:"]
    if admission:
        lines.insert(1, 'apiKeys: ["${env.LARIO_BACKEND_KEY}"]')
    for key, model in models.items():
        aliases = model.get("aliases", []) + (registry["aliases"] if key == active else [])
        args = [registry["binary"], "--host", "127.0.0.1" if admission else "::", "--port", "${PORT}",
                "-fa", "on", "--jinja", *registry.get("extra_args", []),
                *model["args"], "-c", str(model["context"] * model["slots"]),
                "--parallel", str(model["slots"])]
        if admission:
            args += ["--api-key-file", registry["backend_key_file"]]
        # llama-swap replaces ${PORT} before executing the command.
        lines += [f"  {json.dumps(key)}:", f"    aliases: {json.dumps(aliases)}",
                  "    cmd: |", "      " + shlex.join(args), "    ttl: 0",
                  f"    concurrencyLimit: {model['slots']}"]
    lines += ["groups:", "  hardware:", "    swap: true", "    exclusive: true",
              f"    members: {json.dumps(list(models))}"]
    return "\n".join(lines) + "\n"


def api(reg, path, body=None, timeout=5):
    data = None if body is None else json.dumps(body).encode()
    headers = {"Content-Type": "application/json"}
    if os.environ.get("LARIO_BACKEND_KEY"):
        headers["Authorization"] = "Bearer " + os.environ["LARIO_BACKEND_KEY"]
    port = reg.get("backend_port", reg["port"]) if os.environ.get("LARIO_ADMISSION_ENABLED") == "1" else reg["port"]
    req = urllib.request.Request(f"http://127.0.0.1:{port}{path}", data=data, headers=headers)
    with urllib.request.urlopen(req, timeout=timeout) as res:
        # llama-swap's health endpoint is plain text, unlike its model APIs.
        if path == "/health":
            return res.read().decode().strip()
        return json.load(res)


def current(reg):
    # /running is authoritative: a client can request a concrete model directly.
    running = api(reg, "/running").get("running", [])
    ready = [m["model"] for m in running if m.get("state") == "ready"]
    if len(ready) != 1 or ready[0] not in reg["models"]:
        raise RuntimeError("no single registered model is ready; fleet budget unavailable")
    return ready[0]


def fleet_capacity(slots, reserved, context):
    # Hermes primary models require >=64000 client tokens plus the 4096 margin.
    return slots - reserved if context >= 68096 else 0


def runtime_budget(reg):
    running = api(reg, "/running").get("running", [])
    ready = [m for m in running if m.get("state") == "ready"]
    if len(running) != 1 or len(ready) != 1 or ready[0]["model"] not in reg["models"]:
        raise RuntimeError("no single registered model is ready; fleet budget unavailable")
    item = ready[0]
    args = shlex.split(item["cmd"])
    slots = int(args[args.index("--parallel") + 1])
    total = int(args[args.index("-c") + 1])
    if slots < 1 or total < 4096 or total % slots:
        raise RuntimeError("invalid live context geometry")
    reserved = reg["models"][item["model"]]["reserved"]
    if reserved > slots:
        raise RuntimeError("live slots are smaller than reservations")
    return {"model": item["model"], "slots": slots, "reserved": reserved,
            "context": total // slots, "agents": fleet_capacity(slots, reserved, total // slots), "source": "running-process",
            "kv_offload": "--no-kv-offload" not in args,
            "cache_k": args[args.index("-ctk")+1] if "-ctk" in args else "binary-default",
            "cache_v": args[args.index("-ctv")+1] if "-ctv" in args else "binary-default"}


def live_budget(reg):
    if os.environ.get("LARIO_ADMISSION_ENABLED") == "1":
        with urllib.request.urlopen(f"http://127.0.0.1:{reg['port']}/budget", timeout=5) as response:
            return json.load(response)
    return runtime_budget(reg)


def load_runtime(reg):
    path = Path.home() / ".config/lario-admission" / (reg["aliases"][0] + ".env")
    if not path.exists():
        return
    values = dict(line.split("=", 1) for line in path.read_text().splitlines()
                  if line.startswith("LARIO_") and "=" in line)
    if values.get("LARIO_ADMISSION_ENABLED") == "1":
        os.environ.update(values)


def resident_slots(reg, item):
    """Native inspection goes directly to the resident child, never auto-loads a model."""
    parsed = urlparse(item["proxy"])
    if parsed.scheme != "http" or parsed.hostname not in ("localhost", "127.0.0.1", "::1"):
        raise RuntimeError("unexpected resident endpoint")
    if "container" in reg:
        # Container child ports are private. Check the same model remains resident
        # before using the authenticated proxy's monitoring route.
        if current(reg) != item["model"]:
            raise RuntimeError("resident changed during inspection")
        return api(reg, "/upstream/" + quote(item["model"], safe="") + "/slots")
    headers = {}
    if os.environ.get("LARIO_ADMISSION_ENABLED") == "1":
        headers["Authorization"] = "Bearer " + os.environ["LARIO_BACKEND_KEY"]
    request = urllib.request.Request(item["proxy"] + "/slots", headers=headers)
    with urllib.request.urlopen(request, timeout=5) as response:
        return json.load(response)


def assert_idle(reg):
    running = api(reg, "/running").get("running", [])
    for item in running:
        if item.get("state") != "ready":
            raise RuntimeError("backend is transitioning; refusing to stop it")
        slots = resident_slots(reg, item)
        if not isinstance(slots, list) or not slots or any(s.get("is_processing") is not False for s in slots):
            raise RuntimeError("active or unknown inference; refusing to stop hardware")
    if api(reg, "/running").get("running", []) != running:
        raise RuntimeError("resident changed during inspection; refusing to stop hardware")


def assert_not_held(reg):
    path = ROOT / ".deployment-holds.json"
    if path.exists() and reg["aliases"][0] in json.loads(path.read_text()):
        raise RuntimeError("hardware is held by the user; no switching or deployment until explicitly released")



def assert_device_ready(reg):
    # A completion can still succeed after a fatal NVIDIA management fault.
    # Do not certify CUDA hardware from the proxy's ready state alone.
    if reg['aliases'][0]!='rtx5080' or socket.gethostname().split('.')[0]!=reg['host']:
        return
    try:
        result=subprocess.run(['nvidia-smi','--query-gpu=name','--format=csv,noheader'],
                              capture_output=True,text=True,timeout=10)
    except (OSError,subprocess.TimeoutExpired) as error:
        raise RuntimeError('RTX device health unavailable; verify driver recovery before switching or testing') from error
    if result.returncode or 'RTX 5080' not in result.stdout:
        raise RuntimeError('RTX device health failed; proxy readiness is insufficient, verify driver recovery')


def admission_admin(reg, operation):
    if os.environ.get("LARIO_ADMISSION_ENABLED") != "1":
        return
    req = urllib.request.Request(f"http://127.0.0.1:{reg['port']}/admin/{operation}", data=b"{}",
                                 headers={"Authorization": "Bearer " + os.environ["LARIO_MANAGEMENT_KEY"],
                                          "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=10) as response:
        budget = json.load(response)
    if operation == "drain" and sum(budget.get("active", {}).values()):
        raise RuntimeError("active admission requests; hardware left running and drained")


def restart(reg):
    if "container" in reg:
        subprocess.run(["docker", "restart", reg["container"]], check=True,
                       stdout=subprocess.DEVNULL)
    else:
        subprocess.run(["systemctl", "--user", "restart", reg["service"]], check=True)


def warm(reg, key):
    assert_device_ready(reg)
    if key not in reg["models"] and key not in reg["aliases"]:
        raise ValueError(f"unknown warmup model: {key}")
    for _ in range(30):
        try:
            api(reg, "/health")
            break
        except Exception:
            time.sleep(1)
    else:
        raise RuntimeError("model proxy did not become healthy for warmup")
    response = api(reg, "/v1/chat/completions", {
        "model": key, "messages": [{"role": "user", "content": "Reply OK."}],
        "max_tokens": 32, "chat_template_kwargs": {"enable_thinking": False}}, timeout=1800)
    if not response.get("choices"):
        raise RuntimeError(f"warmup did not return a completion: {response}")
    ready = current(reg)
    if key in reg["models"] and ready != key:
        raise RuntimeError("warmup finished without the selected model ready")


def switch(reg, key, preset="capacity", admission=False):
    assert_not_held(reg)
    assert_device_ready(reg)
    config = ROOT / reg["config"]
    state = ROOT / reg["state"]
    previous = config.read_text() if config.exists() else None
    previous_key, previous_preset = selection(reg)
    # Validate the complete replacement before disturbing the running model.
    text = render(reg, key, preset, admission)
    admission_admin(reg, "drain")
    assert_idle(reg)
    try:
        # Stop first: watch-config must not race a rewrite and leave old weights resident.
        if "container" in reg:
            subprocess.run(["docker", "stop", reg["container"]], check=True,
                           stdout=subprocess.DEVNULL)
        else:
            subprocess.run(["systemctl", "--user", "stop", reg["service"]], check=True)
        atomic(config, text)
        save_selection(reg, key, preset)
        restart(reg)
        warm(reg, key)
        save_selection(reg, key, preset)
        admission_admin(reg, "resume")
        print(f"{reg['aliases'][0]} -> {key}: ready", flush=True)
    except Exception:
        if previous is not None:
            print("Switch failed; restoring previous configuration.", file=sys.stderr, flush=True)
            atomic(config, previous)
            save_selection(reg, previous_key, previous_preset)
            restart(reg)
            if previous_key in reg["models"]:
                warm(reg, previous_key)
            save_selection(reg, previous_key, previous_preset)
            admission_admin(reg, "resume")
        raise


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("hardware", choices=["geekom", "7900xt", "rtx5080"])
    parser.add_argument("command", nargs="?", default="menu")
    parser.add_argument("model", nargs="?")
    parser.add_argument("--preset")
    parser.add_argument("--experimental", action="store_true")
    parser.add_argument("--admission", action="store_true", help="render private authenticated backends (deployment only)")
    a = parser.parse_args()
    reg = json.loads((ROOT / a.hardware / "models.json").read_text())
    load_runtime(reg)
    admission = a.admission or os.environ.get("LARIO_ADMISSION_ENABLED") == "1"
    state = ROOT / reg["state"]
    selected, saved_preset = selection(reg)
    preset = a.preset or saved_preset
    models = effective_models(reg, preset)
    command = a.command
    if command == "list":
        for name, model in models.items():
            print(f"{'*' if name == selected else ' '} {name:24} {model['slots']} x "
                  f"{model['context']} tokens; {model['reserved']} reserved")
        return
    if command == "render":
        print(render(reg, a.model or selected, preset, admission), end="")
        return
    if command == "presets":
        print(json.dumps(reg.get("presets", {"capacity": {}}), indent=2))
        return
    if command == "options":
        print_options(reg, selected, saved_preset)
        return
    if command in ("slots", "reserved", "context", "budget"):
        model = live_budget(reg)
        if command == "budget":
            print(json.dumps(model))
        else:
            print(model.get(command, 0))
        return
    if command in ("show", "status"):
        print(f"selected {a.hardware}: {selected} ({saved_preset})")
        print(json.dumps(api(reg, "/running"), indent=2))
        return
    if socket.gethostname().split(".")[0] != reg["host"]:
        raise RuntimeError(f"run {a.hardware} on {reg['host']}")
    if command in ("drain", "resume"):
        admission_admin(reg, command)
        return
    if command == "warm":
        assert_not_held(reg)
        # During a switch, state still records the last successful selection.
        # The hardware alias follows the new proxy config, so startup warmup
        # must use that alias rather than loading the previous model again.
        warm(reg, a.model or reg["aliases"][0])
        return
    if command == "menu":
        if sys.stdin.isatty():
            print_options(reg, selected, saved_preset)
            choice = input("Select option number or model@preset (blank cancels): ").strip()
            if not choice:
                return
            command = choice
            if choice.isdigit() or "@" in choice:
                # Choosing a clearly labelled experimental menu option is explicit.
                a.experimental = True
        else:
            raise RuntimeError("interactive menu needs a terminal; use list or a model name")
    key = (a.model or selected) if command in ("config", "switch") else command
    key, option_preset = resolve_option(reg, key)
    if option_preset:
        if a.preset and a.preset != option_preset:
            raise ValueError("option and --preset disagree")
        preset = option_preset
    # Retain old selection spellings while advertising only the rationalised registry.
    key = {"qwen3.8-fast": "qwen3.8-medium", "qwen3.8-fast-128k": "qwen3.8-medium-128k",
           "qwen38": "qwen3.8", "vision": "ocr"}.get(key, key)
    if a.hardware == "geekom" and key == "qwen3.8":
        key = "qwen3.8-medium"
    if key not in reg["models"]:
        raise ValueError(f"unknown model {key}; use list")
    if not a.preset and not option_preset and preset != "capacity" and key not in reg.get("presets", {}).get(preset, {}).get("models", {}):
        preset = "capacity"
    if (reg.get("presets", {}).get(preset, {}).get("experimental") and not a.experimental
            and not (command == "config" and key == selected and preset == saved_preset)):
        raise RuntimeError("preset is unpromoted; pass --experimental for controlled evaluation")
    # A native unit's ExecStartPre calls config while the switching parent holds
    # the lock. It can read an already correct file without acquiring that lock.
    # Only an exact match returns early; any actual rewrite still needs the lock.
    if command == "config":
        config = ROOT / reg["config"]
        if config.exists() and config.read_text() == render(reg, key, preset, admission):
            return
    with (ROOT / ("." + a.hardware + ".lock")).open("w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        if command == "config":
            # Provisioning only. Never trigger watch-config against a resident model.
            try:
                running = api(reg, "/running").get("running", [])
            except OSError:
                running = []
            if running:
                raise RuntimeError("models are resident; use switch instead of config")
            assert_not_held(reg)
            atomic(ROOT / reg["config"], render(reg, key, preset, admission))
            save_selection(reg, key, preset)
        else:
            switch(reg, key, preset, admission)


if __name__ == "__main__":
    try:
        main()
    except (Exception, KeyboardInterrupt) as exc:
        print(f"modelctl: {exc}", file=sys.stderr)
        sys.exit(1)
