#!/usr/bin/env python3
"""Build portable, offline HTML guides from their canonical Markdown sources."""
import argparse
from datetime import date
import html
from pathlib import Path
import sys

import markdown

ROOT = Path(__file__).resolve().parents[1]
STYLE = '''
:root{color-scheme:light dark;--bg:#f4f7fb;--surface:#fff;--text:#192a3c;--muted:#4e6377;--line:#d8e2ec;--accent:#1263a3;--code:#eef3f8}
@media(prefers-color-scheme:dark){:root{--bg:#101a25;--surface:#172536;--text:#e1eaf4;--muted:#b3c4d8;--line:#34495e;--accent:#82c4ff;--code:#122031}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.65 system-ui,sans-serif}
a{color:var(--accent);text-underline-offset:3px}a:hover{text-decoration-thickness:2px}.skip{position:absolute;left:1rem;top:-5rem}.skip:focus{top:.5rem;background:var(--surface);padding:.5rem}
header{border-bottom:1px solid var(--line);background:var(--surface);padding:1.5rem max(5vw,1rem)}.brand{font-size:.82rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:var(--muted)}nav{display:flex;gap:1.5rem;flex-wrap:wrap;margin-top:.75rem}nav a{font-weight:650}
.layout{max-width:1500px;margin:auto;display:grid;grid-template-columns:235px minmax(0,1fr);gap:2.5rem;padding:2rem 4vw}aside{position:sticky;top:1rem;align-self:start;font-size:.86rem;max-height:95vh;overflow:auto}aside ul{list-style:none;padding-left:1rem}aside>div>ul{padding-left:0}aside li{margin:.55rem 0}aside a{text-decoration:none}.contents-title{font-weight:750;color:var(--muted)}
main{min-width:0;background:var(--surface);padding:2rem 2.5rem;border:1px solid var(--line);border-radius:16px;box-shadow:0 8px 35px #00000006}h1{font-size:clamp(2rem,3.4vw,3rem);line-height:1.15;margin:.25rem 0 1.4rem;letter-spacing:-.03em}h2{font-size:1.5rem;line-height:1.3;margin:2.8rem 0 1rem;padding-top:.5rem;border-top:1px solid var(--line)}h3{font-size:1.1rem;margin-top:2rem}p{max-width:85ch}li{margin:.5rem 0}code{font: .9em ui-monospace,monospace;background:var(--code);padding:.16em .3em;border-radius:4px;overflow-wrap:anywhere}pre{background:var(--code);border:1px solid var(--line);padding:1rem;border-radius:10px;overflow:auto}pre code{padding:0;overflow-wrap:normal}blockquote{margin:1.5rem 0;padding:1rem 1.25rem;border-left:4px solid #ce820d;background:var(--code)}blockquote p{margin:.3rem 0}
.table-wrap{overflow-x:auto;margin:1.3rem 0;border:1px solid var(--line);border-radius:10px}table{border-collapse:collapse;width:100%;font-size:.91rem}th,td{text-align:left;vertical-align:top;padding:.85rem 1rem;border-bottom:1px solid var(--line)}th{background:var(--code);font-weight:750;white-space:normal}tr:last-child td{border-bottom:0}tbody tr:nth-child(even){background:var(--bg)}td code{font-size:.86em}footer{max-width:1500px;margin:auto;padding:0 4vw 2rem;color:var(--muted);font-size:.85rem}.source{color:var(--muted);font-size:.85rem}.search{margin:0 0 1.5rem}.search label{font-weight:650;display:block;margin-bottom:.35rem}.search input{width:100%;max-width:600px;padding:.8rem 1rem;border:1px solid var(--line);border-radius:8px;font:inherit;background:var(--bg);color:var(--text)}[hidden]{display:none!important}
@media(max-width:900px){.layout{grid-template-columns:1fr;padding:1rem}aside{position:static;max-height:none}aside .toc{display:none}main{padding:1.5rem}h1{font-size:2.1rem}.table-wrap{margin-inline:-.4rem}}@media print{header,aside,.search{display:none}.layout{display:block;padding:0}main{border:0;padding:0;box-shadow:none}body{background:white;color:black}a{color:black}table{font-size:10pt}pre{white-space:pre-wrap}h2{break-after:avoid}tr{break-inside:avoid}}
'''
SCRIPT = '''
document.querySelectorAll('table').forEach(table=>{const wrap=document.createElement('div');wrap.className='table-wrap';table.parentNode.insertBefore(wrap,table);wrap.appendChild(table)});
const search=document.querySelector('#model-search');if(search)search.addEventListener('input',()=>{const q=search.value.trim().toLowerCase();document.querySelectorAll('tbody tr').forEach(row=>row.hidden=q&&!row.textContent.toLowerCase().includes(q))});
'''


def page(source, title, benchmark_name):
    md = markdown.Markdown(extensions=['tables', 'fenced_code', 'toc', 'sane_lists'])
    body = md.convert(source.read_text())
    for old, new in [('guide.md', 'guide.html'), ('mcp-guide.md', 'mcp-guide.html'),
                     (benchmark_name, 'benchmarks.html')]:
        body = body.replace('href="'+old, 'href="'+new)
    search = ('<div class="search"><label for="model-search">Find a model or workload</label>'
              '<input id="model-search" type="search" placeholder="Try translation, Radeon or Qwen" autocomplete="off"></div>') if source.name == 'guide.md' else ''
    return f'''<!doctype html>
<!-- GENERATED by scripts/build_docs.py from {source.relative_to(ROOT)}. Edit the Markdown source. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Local AI fleet models, measured benchmarks and MCP operation.">
<title>{html.escape(title)} · Local AI fleet</title><style>{STYLE}</style></head>
<body><a class="skip" href="#content">Skip to content</a><header><div class="brand">Lario · Local AI fleet</div>
<nav aria-label="Documentation"><a href="guide.html">Models &amp; uses</a><a href="benchmarks.html">Benchmarks</a><a href="mcp-guide.html">MCP guide</a></nav></header>
<div class="layout"><aside aria-label="On this page"><div class="contents-title">On this page</div>{md.toc}</aside>
<main id="content">{search}{body}<p class="source">Source: <a href="{html.escape(source.name)}">{html.escape(source.name)}</a></p></main></div>
<footer>Works offline · No external fonts, scripts or tracking · Print with your browser</footer><script>{SCRIPT}</script></body></html>
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--date', type=date.fromisoformat, default=date.today())
    parser.add_argument('--check', action='store_true', help='fail if generated pages differ; write nothing')
    args = parser.parse_args()
    bench = f'benchmarks-{args.date.isoformat()}.md'
    pages = [('guide.md', 'guide.html', 'Models and uses'),
             ('mcp-guide.md', 'mcp-guide.html', 'MCP guide'),
             (bench, 'benchmarks.html', f'Benchmarks — {args.date.isoformat()}'),
             (bench, bench.replace('.md','.html'), f'Benchmarks — {args.date.isoformat()}')]
    failed = False
    for source, destination, title in pages:
        target = ROOT/'docs'/destination
        rendered = page(ROOT/'docs'/source, title, bench)
        if args.check:
            if not target.exists() or target.read_text() != rendered:
                print('stale:', target.relative_to(ROOT));failed = True
        else:
            target.write_text(rendered)
            print('built:', target.relative_to(ROOT))
    if failed:sys.exit(1)


if __name__ == '__main__':main()
